apiVersion: v1
kind: Service
metadata:
  name: filemanager-svc
  labels:
    app: filemanager-app
spec:
  selector:
    app: filemanager-app
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer